# -*- coding: utf-8 -*-
"""project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjCUjbvS5wMXkcpA0w4zCenNN9gGNZ6o
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/data_2.xlsx")
print(data.head(5))
print(data.info())

plt.figure()
plt.hist(data["Sales"], bins=10)
plt.title("Sales Distribution - Histogram")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("sales_histogram.png")
plt.close()

plt.figure()
data["Sales"].plot(kind="kde")
plt.title("Sales Distribution - KDE")
plt.xlabel("Sales")
plt.tight_layout()
plt.savefig("sales_kde.png")
plt.close()

plt.figure()
plt.boxplot(data["Sales"], vert=False)
plt.title("Sales Boxplot (Overall)")
plt.xlabel("Sales")
plt.tight_layout()
plt.savefig("sales_boxplot.png")
plt.close()

plt.figure()
data.boxplot(column="Sales", by="Region")
plt.title("Sales Distribution by Region")
plt.suptitle("")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("sales_by_region_boxplot.png")
plt.close()

Q1 = data["Sales"].quantile(0.25)
Q3 = data["Sales"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = data[(data["Sales"] < lower_bound) | (data["Sales"] > upper_bound)]
print(outliers)

skewness = data["Sales"].skew()
spread = data["Sales"].std()

print("Skewness:", skewness)
print("Standard Deviation:", spread)

interpretation = f"""
The sales distribution is right-skewed, as shown by the histogram and KDE plot.
The standard deviation of {spread:.2f} indicates high variability in sales values.
Boxplots reveal {len(outliers)} potential outliers identified using the IQR method.
Region-wise comparison highlights noticeable differences in median sales and spread,
indicating regional variation in sales performance.
"""

print(interpretation)